{
 "about": {
  "channels": [
   "https://conda.anaconda.org/conda-forge/linux-64",
   "https://conda.anaconda.org/conda-forge/noarch",
   "https://repo.continuum.io/pkgs/free/linux-64",
   "https://repo.continuum.io/pkgs/free/noarch",
   "https://repo.continuum.io/pkgs/pro/linux-64",
   "https://repo.continuum.io/pkgs/pro/noarch"
  ],
  "conda_build_version": "2.1.10",
  "conda_env_version": "4.2.13",
  "conda_private": false,
  "conda_version": "4.2.13",
  "env_vars": {
   "CIO_TEST": "<not set>",
   "CONDA_DEFAULT_ENV": "root",
   "CONDA_ENVS_PATH": "<not set>",
   "LD_LIBRARY_PATH": "/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib",
   "PATH": "/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin",
   "PYTHONHOME": "<not set>",
   "PYTHONPATH": "/opt/rh/devtoolset-2/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-2/root/usr/lib/python2.6/site-packages"
  },
  "home": "https://github.com/landscapeio/pylint-django",
  "license": "GPL 2",
  "offline": false,
  "root_pkgs": [
   "conda-forge::anaconda-client-1.5.1-py35_0",
   "conda-forge::beautifulsoup4-4.5.3-py35_0",
   "conda-forge::ca-certificates-2017.1.23-0",
   "conda-forge::certifi-2017.1.23-py35_0",
   "conda-forge::chardet-3.0.2-py35_0",
   "conda-forge::clyent-1.2.1-py35_0",
   "conda-forge::conda-4.2.13-py35_0",
   "conda-forge::conda-build-2.1.10-py35_0",
   "conda-forge::conda-env-2.6.0-0",
   "conda-forge::conda-forge-build-setup-4.4.4-0",
   "conda-forge::conda-verify-2.0.0-py35_0",
   "conda-forge::curl-7.52.1-0",
   "conda-forge::expat-2.1.0-2",
   "conda-forge::filelock-2.0.6-py35_0",
   "conda-forge::git-2.12.2-4",
   "conda-forge::jinja2-2.9.5-py35_0",
   "conda-forge::libiconv-1.14-4",
   "conda-forge::markupsafe-0.23-py35_1",
   "conda-forge::ncurses-5.9-10",
   "conda-forge::obvious-ci-0.6.1-py35_2",
   "conda-forge::openssl-1.0.2k-0",
   "conda-forge::patchelf-0.9-1",
   "conda-forge::pip-9.0.1-py35_0",
   "conda-forge::pkginfo-1.2.1-py35_0",
   "conda-forge::pycosat-0.6.1-py35_0",
   "conda-forge::pycrypto-2.6.1-py35_0",
   "conda-forge::python-3.5.3-1",
   "conda-forge::python-dateutil-2.6.0-py35_0",
   "conda-forge::pytz-2017.2-py35_0",
   "conda-forge::pyyaml-3.12-py35_1",
   "conda-forge::readline-6.2-0",
   "conda-forge::requests-2.13.0-py35_0",
   "conda-forge::ruamel_yaml-0.11.14-py35_0",
   "conda-forge::setuptools-33.1.1-py35_0",
   "conda-forge::six-1.10.0-py35_1",
   "conda-forge::sqlite-3.13.0-1",
   "conda-forge::tk-8.5.19-1",
   "conda-forge::wheel-0.29.0-py35_0",
   "conda-forge::xz-5.2.2-0",
   "conda-forge::yaml-0.1.6-0",
   "conda-forge::zlib-1.2.11-0"
  ],
  "summary": "pylint-django is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Django framework"
 },
 "conda_build_config": {},
 "files": [
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_db_models.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_db_models_fields_files.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_forms_fields.py",
  "lib/python3.6/site-packages/pylint_django/checkers/models.py",
  "lib/python3.6/site-packages/pylint_django/utils.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_views_generic_base.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_core_handlers_wsgi.py",
  "lib/python3.6/site-packages/pylint_django/__pkginfo__.py",
  "lib/python3.6/site-packages/pylint_django/transforms/__init__.py",
  "lib/python3.6/site-packages/pylint_django/__init__.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_db_models_fields.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_utils_translation.py",
  "lib/python3.6/site-packages/pylint_django-0.7.2-py3.6.egg-info/not-zip-safe",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/mongoengine.py",
  "lib/python3.6/site-packages/pylint_django/compat.py",
  "lib/python3.6/site-packages/pylint_django/plugin.py",
  "lib/python3.6/site-packages/pylint_django-0.7.2-py3.6.egg-info/PKG-INFO",
  "lib/python3.6/site-packages/pylint_django/transforms/foreignkey.py",
  "lib/python3.6/site-packages/pylint_django/checkers/__init__.py",
  "lib/python3.6/site-packages/pylint_django/checkers/django_installed.py",
  "lib/python3.6/site-packages/pylint_django/transforms/fields.py",
  "lib/python3.6/site-packages/pylint_django/augmentations/__init__.py",
  "lib/python3.6/site-packages/pylint_django/transforms/transforms/django_forms.py"
 ],
 "index": {
  "arch": "x86_64",
  "build": "py36_0",
  "build_number": 0,
  "depends": [
   "pylint >=1.0",
   "pylint-plugin-utils >=0.2.1",
   "python 3.6*"
  ],
  "license": "GPL 2",
  "name": "pylint-django",
  "platform": "linux",
  "subdir": "linux-64",
  "version": "0.7.2"
 },
 "metadata_version": 1,
 "name": "pylint-django",
 "raw_recipe": "{% set name = \"pylint-django\" %}\n{% set version = \"0.7.2\" %}\n{% set sha256 = \"b8e51d6b694401e23040ddafc3a4c7da92faaa1718b007ad66aa36e40ec84506\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  fn: {{ name }}-{{ version }}.tar.gz\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: {{ sha256 }}\n\nbuild:\n  number: 0\n  script: python setup.py install --single-version-externally-managed --record=record.txt\n\nrequirements:\n  build:\n    - python\n    - setuptools\n\n  run:\n    - python\n    - pylint-plugin-utils >=0.2.1\n    - pylint >=1.0\n\ntest:\n  imports:\n    - pylint_django\n    - pylint_django.augmentations\n    - pylint_django.checkers\n    - pylint_django.transforms\n\nabout:\n  home: https://github.com/landscapeio/pylint-django\n  license: GPL 2\n  summary: pylint-django is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Django framework\n\nextra:\n  recipe-maintainers:\n    - jakirkham\n",
 "rendered_recipe": {
  "about": {
   "home": "https://github.com/landscapeio/pylint-django",
   "license": "GPL 2",
   "summary": "pylint-django is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Django framework"
  },
  "build": {
   "noarch": "",
   "noarch_python": false,
   "number": "0",
   "script": "python setup.py install --single-version-externally-managed --record=record.txt",
   "string": "py36_0"
  },
  "extra": {
   "final": true,
   "recipe-maintainers": [
    "jakirkham"
   ]
  },
  "package": {
   "name": "pylint-django",
   "version": "0.7.2"
  },
  "requirements": {
   "build": [
    "certifi 2017.1.23 py36_0",
    "zlib 1.2.11 0",
    "setuptools 33.1.1 py36_0",
    "openssl 1.0.2k 0",
    "sqlite 3.13.0 1",
    "ca-certificates 2017.1.23 0",
    "python 3.6.1 0",
    "tk 8.5.19 1",
    "ncurses 5.9 10",
    "readline 6.2 0",
    "xz 5.2.2 0"
   ],
   "run": [
    "python",
    "pylint-plugin-utils >=0.2.1",
    "pylint >=1.0"
   ]
  },
  "source": {
   "fn": "pylint-django-0.7.2.tar.gz",
   "sha256": "b8e51d6b694401e23040ddafc3a4c7da92faaa1718b007ad66aa36e40ec84506",
   "url": "https://pypi.io/packages/source/p/pylint-django/pylint-django-0.7.2.tar.gz"
  },
  "test": {
   "imports": [
    "pylint_django",
    "pylint_django.augmentations",
    "pylint_django.checkers",
    "pylint_django.transforms"
   ]
  }
 },
 "version": "0.7.2"
}