{
 "about": {
  "channels": [
   "https://conda.anaconda.org/conda-forge/linux-64",
   "https://conda.anaconda.org/conda-forge/noarch",
   "https://repo.continuum.io/pkgs/free/linux-64",
   "https://repo.continuum.io/pkgs/free/noarch",
   "https://repo.continuum.io/pkgs/pro/linux-64",
   "https://repo.continuum.io/pkgs/pro/noarch"
  ],
  "conda_build_version": "2.1.10",
  "conda_env_version": "4.2.13",
  "conda_private": false,
  "conda_version": "4.2.13",
  "dev_url": "https://github.com/LuminosoInsight/python-ftfy",
  "doc_url": "http://ftfy.readthedocs.io/",
  "env_vars": {
   "CIO_TEST": "<not set>",
   "CONDA_DEFAULT_ENV": "root",
   "CONDA_ENVS_PATH": "<not set>",
   "LD_LIBRARY_PATH": "/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib",
   "PATH": "/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin",
   "PYTHONHOME": "<not set>",
   "PYTHONPATH": "/opt/rh/devtoolset-2/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-2/root/usr/lib/python2.6/site-packages"
  },
  "home": "https://github.com/LuminosoInsight/python-ftfy/",
  "license": "MIT",
  "offline": false,
  "root_pkgs": [
   "conda-forge::anaconda-client-1.5.1-py35_0",
   "conda-forge::beautifulsoup4-4.5.3-py35_0",
   "conda-forge::ca-certificates-2017.1.23-0",
   "conda-forge::certifi-2017.1.23-py35_0",
   "conda-forge::chardet-3.0.2-py35_0",
   "conda-forge::clyent-1.2.1-py35_0",
   "conda-forge::conda-4.2.13-py35_0",
   "conda-forge::conda-build-2.1.10-py35_0",
   "conda-forge::conda-env-2.6.0-0",
   "conda-forge::conda-forge-build-setup-4.4.4-0",
   "conda-forge::conda-verify-2.0.0-py35_0",
   "conda-forge::curl-7.52.1-0",
   "conda-forge::expat-2.1.0-2",
   "conda-forge::filelock-2.0.6-py35_0",
   "conda-forge::git-2.12.2-4",
   "conda-forge::jinja2-2.9.5-py35_0",
   "conda-forge::libiconv-1.14-4",
   "conda-forge::markupsafe-0.23-py35_1",
   "conda-forge::ncurses-5.9-10",
   "conda-forge::obvious-ci-0.6.1-py35_2",
   "conda-forge::openssl-1.0.2k-0",
   "conda-forge::patchelf-0.9-1",
   "conda-forge::pip-9.0.1-py35_0",
   "conda-forge::pkginfo-1.2.1-py35_0",
   "conda-forge::pycosat-0.6.1-py35_0",
   "conda-forge::pycrypto-2.6.1-py35_0",
   "conda-forge::python-3.5.3-1",
   "conda-forge::python-dateutil-2.6.0-py35_0",
   "conda-forge::pytz-2017.2-py35_0",
   "conda-forge::pyyaml-3.12-py35_1",
   "conda-forge::readline-6.2-0",
   "conda-forge::requests-2.13.0-py35_0",
   "conda-forge::ruamel_yaml-0.11.14-py35_0",
   "conda-forge::setuptools-33.1.1-py35_0",
   "conda-forge::six-1.10.0-py35_1",
   "conda-forge::sqlite-3.13.0-1",
   "conda-forge::tk-8.5.19-1",
   "conda-forge::wheel-0.29.0-py35_0",
   "conda-forge::xz-5.2.2-0",
   "conda-forge::yaml-0.1.6-0",
   "conda-forge::zlib-1.2.11-0"
  ],
  "summary": "Fixes some problems with Unicode text after the fact"
 },
 "conda_build_config": {},
 "files": [
  "lib/python3.5/site-packages/ftfy/badness.py",
  "lib/python3.5/site-packages/ftfy/fixes.py",
  "lib/python3.5/site-packages/ftfy/bad_codecs/__init__.py",
  "lib/python3.5/site-packages/ftfy/char_classes.dat",
  "lib/python3.5/site-packages/ftfy/__init__.py",
  "lib/python3.5/site-packages/ftfy/build_data.py",
  "lib/python3.5/site-packages/ftfy/bad_codecs/utf8_variants.py",
  "lib/python3.5/site-packages/ftfy/cli.py",
  "lib/python3.5/site-packages/ftfy/bad_codecs/sloppy.py",
  "lib/python3.5/site-packages/ftfy/formatting.py",
  "lib/python3.5/site-packages/ftfy-4.4.2-py3.5.egg-info/PKG-INFO",
  "lib/python3.5/site-packages/ftfy/compatibility.py",
  "bin/ftfy",
  "lib/python3.5/site-packages/ftfy/chardata.py"
 ],
 "index": {
  "arch": "x86_64",
  "build": "py35_0",
  "build_number": 0,
  "depends": [
   "html5lib",
   "python 3.5*",
   "setuptools",
   "wcwidth"
  ],
  "license": "MIT",
  "name": "ftfy",
  "platform": "linux",
  "subdir": "linux-64",
  "version": "4.4.2"
 },
 "metadata_version": 1,
 "name": "ftfy",
 "raw_recipe": "{% set name = \"ftfy\" %}\n{% set version = \"4.4.2\" %}\n{% set sha256sum = \"0d82c3c7550d030c0b0e833f9b4d2a3c54873f7a934eec9913694977e3fb165f\" %}\n\npackage:\n  name: {{ name }}\n  version: {{ version }}\n\nsource:\n  fn: {{ name }}-{{ version }}.tar.gz\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: {{ sha256sum }}\n\nbuild:\n  number: 0\n  script: python setup.py install --single-version-externally-managed --record=record.txt\n  entry_points:\n    - ftfy = ftfy.cli:main\n\nrequirements:\n  build:\n    - python\n    - setuptools\n\n  run:\n    - python\n    # Required for loading package data via `pkg_resources` module.\n    - setuptools\n    - html5lib\n    - wcwidth\n\ntest:\n  imports:\n    - ftfy\n    - ftfy.build_data\n    - ftfy.chardata\n    - ftfy.cli\n    - ftfy.fixes\n    - ftfy.formatting\n\n  commands:\n    - ftfy -h\n\nabout:\n  home: https://github.com/LuminosoInsight/python-ftfy/\n  license: MIT\n  license_file: LICENSE.txt\n  summary: Fixes some problems with Unicode text after the fact\n  dev_url: https://github.com/LuminosoInsight/python-ftfy\n  doc_url: http://ftfy.readthedocs.io/\n\nextra:\n  recipe-maintainers:\n    - rolando\n",
 "rendered_recipe": {
  "about": {
   "dev_url": "https://github.com/LuminosoInsight/python-ftfy",
   "doc_url": "http://ftfy.readthedocs.io/",
   "home": "https://github.com/LuminosoInsight/python-ftfy/",
   "license": "MIT",
   "license_file": "LICENSE.txt",
   "summary": "Fixes some problems with Unicode text after the fact"
  },
  "build": {
   "entry_points": [
    "ftfy = ftfy.cli:main"
   ],
   "noarch": "",
   "noarch_python": false,
   "number": "0",
   "script": "python setup.py install --single-version-externally-managed --record=record.txt",
   "string": "py35_0"
  },
  "extra": {
   "final": true,
   "recipe-maintainers": [
    "rolando"
   ]
  },
  "package": {
   "name": "ftfy",
   "version": "4.4.2"
  },
  "requirements": {
   "build": [
    "xz 5.2.2 0",
    "tk 8.5.19 1",
    "certifi 2017.4.17 py35_0",
    "python 3.5.3 1",
    "setuptools 33.1.1 py35_0",
    "zlib 1.2.11 0",
    "ca-certificates 2017.1.23 1",
    "sqlite 3.13.0 1",
    "ncurses 5.9 10",
    "openssl 1.0.2k 0",
    "readline 6.2 0"
   ],
   "run": [
    "python",
    "setuptools",
    "html5lib",
    "wcwidth"
   ]
  },
  "source": {
   "fn": "ftfy-4.4.2.tar.gz",
   "sha256": "0d82c3c7550d030c0b0e833f9b4d2a3c54873f7a934eec9913694977e3fb165f",
   "url": "https://pypi.io/packages/source/f/ftfy/ftfy-4.4.2.tar.gz"
  },
  "test": {
   "commands": [
    "ftfy -h"
   ],
   "imports": [
    "ftfy",
    "ftfy.build_data",
    "ftfy.chardata",
    "ftfy.cli",
    "ftfy.fixes",
    "ftfy.formatting"
   ]
  }
 },
 "version": "4.4.2"
}