{
 "about": {
  "channels": [
   "conda-forge",
   "defaults"
  ],
  "conda_build_version": "3.10.1",
  "conda_private": false,
  "conda_version": "4.5.2",
  "env_vars": {
   "CIO_TEST": "<not set>",
   "CONDA_DEFAULT_ENV": "base",
   "CONDA_ENVS_PATH": "<not set>",
   "LD_LIBRARY_PATH": "/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib",
   "PATH": "/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin",
   "PYTHONHOME": "<not set>",
   "PYTHONPATH": "/opt/rh/devtoolset-2/root/usr/lib64/python2.6/site-packages:/opt/rh/devtoolset-2/root/usr/lib/python2.6/site-packages"
  },
  "home": "https://gnupg.org/software/index.html",
  "license": "GPL-2.0",
  "license_family": "GPL",
  "root_pkgs": [
   "cffi 1.11.5 py36_0",
   "cryptography 2.2.1 py36_0",
   "xz 5.2.3 0",
   "packaging 17.1 py_0",
   "requests 2.18.4 py36_1",
   "certifi 2018.4.16 py36_0",
   "readline 7.0 0",
   "chardet 3.0.4 py36_0",
   "pyopenssl 17.5.0 py36_1",
   "urllib3 1.22 py36_0",
   "zlib 1.2.11 0",
   "yaml 0.1.7 0",
   "pycparser 2.18 py36_0",
   "asn1crypto 0.24.0 py36_0",
   "libffi 3.2.1 3",
   "tk 8.6.7 0",
   "setuptools 39.0.1 py36_0",
   "ruamel_yaml 0.15.35 py36_0",
   "pysocks 1.6.8 py36_1",
   "pip 9.0.3 py36_0",
   "idna 2.6 py36_1",
   "wheel 0.31.0 py36_0",
   "python 3.6.5 1",
   "pycosat 0.6.3 py36_0",
   "ncurses 5.9 10",
   "six 1.11.0 py36_1",
   "ca-certificates 2018.4.16 0",
   "pyparsing 2.2.0 py36_0",
   "sqlite 3.20.1 2",
   "conda-env 2.6.0 0",
   "openssl 1.0.2o 0",
   "traitlets 4.3.2 py36_0",
   "pytz 2018.4 py_0",
   "git 2.14.2 3",
   "curl 7.59.0 1",
   "glob2 0.5 py36_0",
   "conda-verify 2.0.0 py36_0",
   "filelock 3.0.4 py36_0",
   "jsonschema 2.6.0 py36_1",
   "anaconda-client 1.6.14 py_0",
   "pyyaml 3.12 py36_1",
   "beautifulsoup4 4.6.0 py36_0",
   "patchelf 0.9 2",
   "clyent 1.2.2 py36_0",
   "tini 0.18.0 0",
   "ipython_genutils 0.2.0 py36_0",
   "libiconv 1.15 0",
   "krb5 1.14.6 0",
   "expat 2.2.5 0",
   "nbformat 4.4.0 py36_0",
   "decorator 4.3.0 py_0",
   "conda-forge-ci-setup 1.3.3 0",
   "libssh2 1.8.0 2",
   "conda-build 3.10.1 py36_0",
   "pkginfo 1.4.2 py36_0",
   "jinja2 2.10 py36_0",
   "conda 4.5.2 py36_0",
   "jupyter_core 4.4.0 py_0",
   "markupsafe 1.0 py36_0",
   "psutil 5.4.5 py36_0",
   "python-dateutil 2.7.2 py_0",
   "gosu 1.10 0"
  ],
  "summary": "a small library that originally defined common error values for all GnuPG components"
 },
 "conda_build_config": {
  "c_compiler": "gcc",
  "cpu_optimization_target": "nocona",
  "cxx_compiler": "gxx",
  "fortran_compiler": "gfortran",
  "ignore_build_only_deps": "python",
  "lua": "5",
  "numpy": "1.11",
  "perl": "5.26.0",
  "pin_run_as_build": {
   "python": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   },
   "r-base": {
    "max_pin": "x.x.x",
    "min_pin": "x.x.x"
   }
  },
  "python": "3.6",
  "r_base": "3.4",
  "target_platform": "linux-64"
 },
 "files": [
  "bin/gpg-error",
  "bin/gpg-error-config",
  "bin/gpgrt-config",
  "bin/yat2m",
  "include/gpg-error.h",
  "include/gpgrt.h",
  "lib/libgpg-error.la",
  "lib/libgpg-error.so",
  "lib/libgpg-error.so.0",
  "lib/libgpg-error.so.0.24.2",
  "share/aclocal/gpg-error.m4",
  "share/aclocal/gpgrt.m4",
  "share/common-lisp/source/gpg-error/gpg-error-codes.lisp",
  "share/common-lisp/source/gpg-error/gpg-error-package.lisp",
  "share/common-lisp/source/gpg-error/gpg-error.asd",
  "share/common-lisp/source/gpg-error/gpg-error.lisp",
  "share/info/gpgrt.info",
  "share/locale/cs/LC_MESSAGES/libgpg-error.mo",
  "share/locale/da/LC_MESSAGES/libgpg-error.mo",
  "share/locale/de/LC_MESSAGES/libgpg-error.mo",
  "share/locale/eo/LC_MESSAGES/libgpg-error.mo",
  "share/locale/es/LC_MESSAGES/libgpg-error.mo",
  "share/locale/fr/LC_MESSAGES/libgpg-error.mo",
  "share/locale/hu/LC_MESSAGES/libgpg-error.mo",
  "share/locale/it/LC_MESSAGES/libgpg-error.mo",
  "share/locale/ja/LC_MESSAGES/libgpg-error.mo",
  "share/locale/nl/LC_MESSAGES/libgpg-error.mo",
  "share/locale/pl/LC_MESSAGES/libgpg-error.mo",
  "share/locale/pt/LC_MESSAGES/libgpg-error.mo",
  "share/locale/ro/LC_MESSAGES/libgpg-error.mo",
  "share/locale/ru/LC_MESSAGES/libgpg-error.mo",
  "share/locale/sr/LC_MESSAGES/libgpg-error.mo",
  "share/locale/sv/LC_MESSAGES/libgpg-error.mo",
  "share/locale/uk/LC_MESSAGES/libgpg-error.mo",
  "share/locale/vi/LC_MESSAGES/libgpg-error.mo",
  "share/locale/zh_CN/LC_MESSAGES/libgpg-error.mo",
  "share/locale/zh_TW/LC_MESSAGES/libgpg-error.mo",
  "share/man/man1/gpg-error-config.1"
 ],
 "index": {
  "arch": "x86_64",
  "build": "hf484d3e_0",
  "build_number": 0,
  "depends": [
   "libgcc-ng >=7.2.0",
   "libstdcxx-ng >=7.2.0"
  ],
  "license": "GPL-2.0",
  "license_family": "GPL",
  "name": "libgpg-error",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1525392456749,
  "version": "1.31"
 },
 "metadata_version": 1,
 "name": "libgpg-error",
 "raw_recipe": "{% set name = \"libgpg-error\" %}\n{% set version = \"1.31\" %}\n{% set sha256 = \"40d0a823c9329478063903192a1f82496083b277265904878f4bc09e0db7a4ef\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://gnupg.org/ftp/gcrypt/libgpg-error/{{ name }}-{{ version }}.tar.bz2\n  sha256: {{ sha256 }}\n\nbuild:\n  number: 0\n  skip: True  # [win]\n  run_exports:\n   - {{ pin_subpackage('libgpg-error') }}\n\nrequirements:\n  build:\n    - {{ compiler('c') }}\n    - {{ compiler('cxx') }}\n\ntest:\n  commands:\n    - test -f $PREFIX/lib/libgpg-error.so  # [linux]\n    - conda inspect linkages {{ name }}\n    - conda inspect objects {{ name }}  # [osx]\n\nabout:\n  home: https://gnupg.org/software/index.html\n  license: GPL-2.0\n  license_family: GPL\n  summary: 'a small library that originally defined common error values for all GnuPG components'\n\nextra:\n  recipe-maintainers:\n    - martindurant\n    - mariusvniekerk\n",
 "rendered_recipe": {
  "about": {
   "home": "https://gnupg.org/software/index.html",
   "license": "GPL-2.0",
   "license_family": "GPL",
   "summary": "a small library that originally defined common error values for all GnuPG components"
  },
  "build": {
   "number": "0",
   "run_exports": [
    "libgpg-error >=1.31,<2.0a0"
   ],
   "string": "hf484d3e_0"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "mariusvniekerk",
    "martindurant"
   ]
  },
  "package": {
   "name": "libgpg-error",
   "version": "1.31"
  },
  "requirements": {
   "build": [
    "binutils_impl_linux-64 2.28.1 had2808c_3",
    "binutils_linux-64 7.2.0 26",
    "gcc_impl_linux-64 7.2.0 habb00fd_3",
    "gcc_linux-64 7.2.0 26",
    "gxx_impl_linux-64 7.2.0 hdf63c60_3",
    "gxx_linux-64 7.2.0 26",
    "libstdcxx-ng 7.2.0 hdf63c60_3"
   ],
   "host": [
    "libgcc-ng 7.2.0 hdf63c60_3",
    "libstdcxx-ng 7.2.0 hdf63c60_3"
   ],
   "run": [
    "libgcc-ng >=7.2.0",
    "libstdcxx-ng >=7.2.0"
   ]
  },
  "source": {
   "sha256": "40d0a823c9329478063903192a1f82496083b277265904878f4bc09e0db7a4ef",
   "url": "https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.31.tar.bz2"
  },
  "test": {
   "commands": [
    "test -f $PREFIX/lib/libgpg-error.so",
    "conda inspect linkages libgpg-error"
   ]
  }
 },
 "version": "1.31"
}